spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
server:
  port: 8989
springdoc:
  swagger-ui:
    url: /swagger.json